# coding: utf-8
# examples sconscript
#
# $LastChangedDate: 2011-02-21 08:30:11 +0800 (周一, 21 二月 2011) $
# $LastChangedBy: davide.bacchet@gmail.com $


import os,sys

Import('env')


# build maratis sample app
program = SConscript( 'ManualUse/SConscript', exports='env' )

